        const templates = [
            // Observational / Time-based
            ["Observe the {noun} until it disappears."],
            ["Stare at the {noun} until you can no longer recognize it."],
            ["Listen to the {noun} for exactly one year."],
            ["Imagine a {noun} in an empty room.", "Do not open the door."],
            ["Wait for the {noun} to make a sound.", "Leave immediately."],
            ["Sit with the {noun} in total silence."],
            ["Watch a {noun} grow old."],
            ["Measure the distance between two {noun}s."],
            ["Wait for the {noun} to forget you."],
            ["Watch the {noun} for three days and nights."],
            ["Look at the {noun} through a magnifying glass until it burns."],
            ["Wait for the {noun} to fall asleep."],
            ["Spend the rest of your life watching the {noun}."],
            ["Listen to the {noun} rust."],
            ["Watch a {noun} pass by.", "Record the time."],
            ["Count the seconds it takes for a {noun} to move."],
            ["Monitor the {noun} for signs of life."],
            ["Wait until the {noun} changes its shape."],
            ["Observe the {noun} until you know its history."],
            ["Look at the {noun} and do nothing else."],
            
            // Destructive / Transformative
            ["Take a {noun}.", "Cut it into 1000 pieces.", "Throw them into the wind."],
            ["Bury the {noun}.", "Dig it up in 10 years."],
            ["Light a match.", "Watch the {noun} burn.", "Collect the ashes."],
            ["Melt the {noun}."],
            ["Paint the {noun} completely black."],
            ["Boil the {noun}.", "Drink the water."],
            ["Wrap the {noun} in white paper.", "Never open it."],
            ["Drop the {noun} on a hard floor.", "Sweep it up."],
            ["Wash the {noun} until there is nothing left."],
            ["Let a {noun} slowly dissolve in rain."],
            ["Crush the {noun} with a heavy stone."],
            ["Freeze the {noun}.", "Send it to a warm country."],
            ["Tear the {noun} in half.", "Give one half to a stranger."],
            ["Paint the {noun} the color of the sky."],
            ["Leave the {noun} in the sun until its color fades."],
            ["Bite the {noun}."],
            ["Dismantle the {noun}.", "Hide the pieces in different rooms."],
            ["Burn the {noun} and inhale the smoke."],
            ["Flatten the {noun} with a heavy book."],
            ["Erase the {noun} from existence."],

            // Relational / Social
            ["Send a {noun} to a friend.", "Wait for a reply."],
            ["Exchange your {noun} with a stranger."],
            ["Give the {noun} to the first person you meet."],
            ["Tell a secret to the {noun}.", "Forget the secret."],
            ["Mail a {noun} to yourself."],
            ["Leave a {noun} on a train."],
            ["Ask someone about their {noun}.", "Do not listen to the answer."],
            ["Steal a {noun}.", "Return it tomorrow."],
            ["Give a {noun} to your worst enemy."],
            ["Apologize to the {noun} for everything."],
            ["Teach the {noun} how to speak."],
            ["Introduce the {noun} to your family."],
            ["Call a random number.", "Read a description of the {noun}.", "Hang up."],
            ["Trade a {noun} for a memory."],
            ["Ask a {noun} to dance."],
            ["Whisper the name of the {noun} to a passerby."],
            ["Follow the {noun} through the streets."],
            ["Share a meal with a {noun}."],
            ["Invite a {noun} to your home.", "Do not speak to it."],
            ["Make a {noun} your successor."],

            // Spatial / Object manipulation
            ["Place the {noun} under a piano."],
            ["Draw a line around the {noun}.", "Never cross the line."],
            ["Put a {noun} inside another {noun}."],
            ["Keep the {noun} in your pocket for a year."],
            ["A {noun} is placed on a pedestal.", "Audience leaves."],
            ["Drop a {noun} from a great height.", "Listen to the impact."],
            ["Nail a {noun} to the wall."],
            ["Hide a {noun} in a museum."],
            ["Carry a {noun} from one room to another."],
            ["Stack {noun}s as high as possible.", "Let them fall."],
            ["Find the exact center of a {noun}."],
            ["Hang a {noun} from the ceiling.", "Lie beneath it."],
            ["Throw the {noun} into the ocean."],
            ["Place the {noun} exactly in the middle of a forest."],
            ["Bury a {noun} under a streetlight."],
            ["Cover the {noun} with dirt."],
            ["Tie a {noun} to a balloon.", "Let it go."],
            ["Build a house for the {noun}."],
            ["Place a {noun} in every corner of the room."],
            ["Balance a {noun} on your head.", "Walk across the bridge."],

            // Conceptual / Absurd / Impossible
            ["Do not think about {noun}."],
            ["Count every {noun} in the world."],
            ["Breathe in.", "Become the {noun}.", "Breathe out."],
            ["Find a {noun}.", "Pretend it is something else."],
            ["A {noun} that cannot be seen.", "A {noun} that cannot be touched."],
            ["Make a {noun} out of ice.", "Watch it return to water."],
            ["Spell the word '{noun}' backwards.", "Repeat until meaningless."],
            ["Try to remember a {noun} you have never seen."],
            ["Sleep next to a {noun}."],
            ["Apologize to a {noun}."],
            ["Make a {noun} out of shadow."],
            ["Think of a {noun}.", "Now forget it."],
            ["Write the word '{noun}' on a piece of paper.", "Eat the paper."],
            ["Draw a map to the nearest {noun}."],
            ["Lift the {noun} with your mind."],
            ["Convince yourself that the {noun} does not exist."],
            ["Walk in the shape of a {noun}."],
            ["Dream about a {noun}."],
            ["Paint a portrait of the {noun}'s mother."],
            ["A {noun} without a shadow."],
            ["Become a {noun} for a day."],
            ["Find the shadow of the {noun}."],
            ["Trace the outline of a {noun} on your palm."],
            ["Declare the {noun} a sovereign nation."],
            ["Calculate the weight of a {noun}."],

            // Sound / Auditory
            ["Make the sound of a {noun}."],
            ["Listen to the {noun} breathing."],
            ["Play a {noun} like an instrument."],
            ["Record the sound of a {noun}.", "Bury the tape."],
            ["A single {noun} drops.", "Silence."],
            ["Sing to the {noun} until it rains."],
            ["Wait for the {noun} to ring."],
            ["Listen to the {noun} over a telephone."],
            ["Tune the {noun} to perfect pitch."],
            ["Scream at the {noun}."],
            ["Hum the melody of a {noun}."],
            ["Record the sound of the {noun} breaking."],
            ["Make the sound of the {noun} falling."],
            ["Clap your hands for the {noun}."],
            ["Use the {noun} to make a rhythmic sound."],

            // Weather / Nature
            ["Wait for the snow to cover the {noun}."],
            ["Show the {noun} to the moon."],
            ["Let the wind carry the {noun} away."],
            ["Water the {noun} every day."],
            ["Plant a {noun}.", "Wait for spring."],
            ["Expose the {noun} to a storm."],
            ["Leave the {noun} out in the rain."],
            ["Let a {noun} dry in the wind."],
            ["Search for a {noun} in the field."],
            ["Offer the {noun} to the earth."],

            // Minimalist / Zen
            ["A {noun}."],
            ["Take the {noun}."],
            ["Leave the {noun}."],
            ["Breathe on it.", "Wait."],
            ["Find its shadow."],
            ["Calculate its weight."],
            ["Paint a portrait of its mother."],
            ["Flatten it with a book."],
            ["Chew it."],
            ["Erase it from the world."],
            ["Wait."],
            ["Stop."],
            ["Begin."],
            ["Nothing but the {noun}."],
            ["on.", "off."],
            ["up.", "down."],
            ["open.", "close."],
            ["in.", "out."],
            ["yes.", "no."],
            ["before.", "after."],
            ["left.", "right."],
            ["here.", "there."],
            ["now.", "then."],
            ["always.", "never."],
            ["one.", "two.", "three."],
            ["red.", "blue.", "yellow."],
            ["wait.", "go."],
            ["empty.", "full."],
            ["silent.", "loud."],
            ["fast.", "slow."],
            ["light.", "dark."],
            ["near.", "far."],
            ["above.", "below."],
            ["inside.", "outside."],
            ["front.", "back."],
            ["start.", "stop.", "start."],
            ["breathe."],
            ["look."],
            ["listen."],
            ["touch."],
            ["drop.", "pick up."],
            ["push.", "pull."],
            ["break.", "fix."],
            ["hide.", "find."],
            ["forget.", "remember."],
            ["nothing.", "something.", "everything."],
            ["Jump."],
            ["Run."],
            ["Sleep."],
            ["Wake."],
            ["Smile."],
            ["Cry."],
            ["Scream."],
            ["Whisper."],
            ["Think."],
            ["Forget."],
            ["Remember."],
            ["Fall."],
            ["Stand."],
            ["Sit."],
            ["Walk."],
            ["Sing."],
            ["Dance."],
            ["Eat."],
            ["Drink."],
            ["Bite."],
            ["Cut."],
            ["Tear."],
            ["Fold."],
            ["Burn."],
            ["Melt."],
            ["Freeze."],
            ["Drop."],
            ["Catch."],
            ["Throw."],
            ["Hold."],
            ["Release."],
            ["Find {noun}."],
            ["Hide {noun}."],
            ["Eat {noun}."],
            ["Drink {noun}."],
            ["Bite {noun}."],
            ["Drop {noun}."],
            ["Watch {noun}."],
            ["Touch {noun}."],
            ["Smell {noun}."],
            ["Taste {noun}."],
            ["Burn {noun}."],
            ["Fold {noun}."],
            ["Tear {noun}."],
            ["Hold {noun}."],
            ["Break {noun}."],
            ["Fix {noun}."],
            ["Love {noun}."],
            ["Forget {noun}."],
            ["Remember {noun}."],
            ["Count {noun}s."],
            ["Stop {noun}."],
            ["Start {noun}."],
            ["Become {noun}."],
            ["top.", "bottom."],
            ["first.", "last."],
            ["one {noun}.", "two {noun}s.", "three {noun}s."],
            ["{noun} A.", "{noun} B."],
            ["point.", "line.", "surface."],
            ["water.", "ice.", "steam."],
            ["solid.", "liquid.", "gas."],
            ["black.", "white."],
            ["day.", "night."],
            ["sun.", "moon.", "stars."],
            ["earth.", "wind.", "fire.", "water."],
            ["Do."],
            ["{noun} is.", "The {noun} is not."],
            ["The {noun} arrives.", "The {noun} departs."],
            ["Empty space.", "A {noun}."],
            ["Nothing but the {noun}."],
            ["It is a {noun}."]
        ,
            // Web / SNS & Multi-line Additions
            ["{noun}をクラウドにアップロードしろ。"],
            ["{noun}をスマートフォンの待受にしろ。"],
            ["{noun}の写真を撮り、誰にも見せずに消せ。"],
            ["ハッシュタグ無しで{noun}と呟け。"],
            ["{noun}に「いいね」を押し、取り消せ。"],
            ["{noun}を即座にブロックしろ。"],
            ["{noun}の検索履歴を完全に消去せよ。"],
            ["{noun}を機内モードで持ち歩け。"],
            ["{noun}のソースコードを音読しろ。"],
            ["見知らぬ他人に{noun}をAirDropしろ。"],
            ["{noun}を既読無視せよ。"],
            ["{noun}の利用規約に同意するな。"],
            ["{noun}のWi-Fiパスワードを推測せよ。"],
            ["息を止めながら、{noun}の角度を測れ。"],
            ["{noun}を結び、忘却をひとつ記録しろ。"],
            ["{noun}の温度が完全に下がるまで待て。"],
            ["無音の部屋で{noun}を数えよ。"],
            ["{noun}を水に溶かして、静かに飲め。"],
            ["{noun}の影をハサミで切り取れ。"],
            ["誰にも見られずに{noun}を土に埋めよ。"],
            ["{noun}の重さと同じだけ空気を吸え。"],
            ["鏡に向かって{noun}を3回朗読せよ。"],
            ["真夜中に{noun}を裏返せ。"],
            ["{noun}の写真を撮る。", "加工する。", "アップロード直前に消す。"],
            ["{noun}のアカウントを作る。", "パスワードを忘れる。", "永遠に放置する。"],
            ["画面をスクロールする。", "{noun}が現れるまで。", "現れたら目を閉じる。"],
            ["Wi-Fiを切る。", "{noun}に話しかける。", "接続エラーを待つ。"],
            ["{noun}をコピーする。", "空のファイルにペーストする。", "保存せずに閉じる。"],
            ["{noun}をミュートする。", "{noun}をブロックする。", "{noun}を忘れる。"],
            ["{noun}をアーカイブする。", "アーカイブを探す。", "見つからない。"],
            ["{noun}を探す。", "見つける。", "見なかったことにする。"],
            ["{noun}を愛する。", "{noun}を憎む。", "どちらでもなくなる。"],
            ["{noun}を作る。", "壊す。", "もう一度作る。"],
            ["{noun}を呼ぶ。", "返事がない。", "それでも呼ぶ。"],
            ["{noun}を燃やす。", "灰を集める。", "風に飛ばす。"],
            ["{noun}を盗む。", "返す。", "また盗む。"],
            ["{noun}を切り裂く。", "縫い合わせる。", "傷跡をなぞる。"]
        ];
