const templates = [
    ["Hide a microscopic {noun}."],
    ["Without thinking, crush a stranger's {noun}."],
    ["For no reason, dissolve the {noun}."],
    ["Find the {noun}.", "Look at it.", "Walk away."],
    ["Smiling, reassemble a forgotten {noun}."],
    ["Without thinking, decode the real {noun}."],
    ["Count a burning {noun}."],
    ["Lick the {noun}."],
    ["In the dark, curse a future {noun}."],
    ["Disconnect Wi-Fi.", "Talk to the {noun}.", "Wait for connection error."],
    ["While falling, empty the {noun}."],
    ["Naked, record a future {noun}."],
    ["Believe in the {noun}.", "Doubt it.", "Forget it."],
    ["Standing on one leg, drop a silent {noun}."],
    ["Walking backwards, mute an imaginary {noun}."],
    ["In the dark, pet your own {noun}."],
    ["With ears covered, compress an imaginary {noun}."],
    ["While falling, weigh the {noun}."],
    ["For a single moment, format a microscopic {noun}."],
    ["Screaming loudly, empty your own {noun}."],
    ["In complete silence, design the first {noun}."],
    ["Upload the {noun}.", "Refresh the page.", "Delete it."],
    ["Like a prayer, destroy a fake {noun}."],
    ["Trembling, bury a perfect {noun}."],
    ["In complete silence, escape from all {noun}s."],
    ["At the perfect time, hate the first {noun}."],
    ["Blindfolded, cut an imaginary {noun}."],
    ["For a single moment, talk to your own {noun}."],
    ["Charge the {noun} to 100%.", "Watch it drain to 0%.", "Hide the charger."],
    ["In secret, record the first {noun}."],
    ["Sing to a silent {noun}."],
    ["Name the {noun}."],
    ["While falling, record a forgotten {noun}."],
    ["Screaming loudly, flip a future {noun}."],
    ["Record a broken {noun}."],
    ["Embrace a fake {noun}."],
    ["At midnight, ignore the {noun}."],
    ["For no reason, reboot your own {noun}."],
    ["Upload a giant {noun}."],
    ["While falling, ignore the {noun}."],
    ["Freeze the {noun}.", "Watch it melt.", "Drink the water."],
    ["Forever, burn a silent {noun}."],
    ["At the perfect time, drop a perfect {noun}."],
    ["Stare at the {noun}."],
    ["Without thinking, lick a burning {noun}."],
    ["Weigh a microscopic {noun}."],
    ["Without any emotion, smell every {noun}."],
    ["For a single moment, lick the {noun}."],
    ["Standing on one leg, curse an imaginary {noun}."],
    ["Love a perfect {noun}."],
    ["Paint a silent {noun}."],
    ["Smash your own {noun}."],
    ["Standing on one leg, step on a perfect {noun}."],
    ["With ears covered, remember your own {noun}."],
    ["While falling, upload the {noun}."],
    ["Holding your breath, flip the first {noun}."],
    ["With eyes closed, cut a giant {noun}."],
    ["Walking backwards, crush every {noun}."],
    ["Blindfolded, reassemble the {noun}."],
    ["Ignore a forgotten {noun}."],
    ["Draw an imaginary {noun}."],
    ["Like a prayer, smell a stranger's {noun}."],
    ["Hit the {noun}.", "Pet the {noun}.", "Apologize."],
    ["Trembling, talk to an imaginary {noun}."],
    ["Smiling, drop all {noun}s."],
    ["Like a prayer, unzip a broken {noun}."],
    ["Blindfolded, delete the last {noun}."],
    ["Crush a fake {noun}."],
    ["Standing on one leg, format all {noun}s."],
    ["Talk to a silent {noun}."],
    ["In the dark, delete the {noun}."],
    ["Draw a future {noun}."],
    ["Record a silent {noun}."],
    ["With eyes closed, pet a fake {noun}."],
    ["While crying, touch a microscopic {noun}."],
    ["Walking backwards, draw the real {noun}."],
    ["While crying, swallow a perfect {noun}."],
    ["In the dark, remember the last {noun}."],
    ["Walking backwards, freeze a silent {noun}."],
    ["Holding your breath, escape from a dead {noun}."],
    ["Share the last {noun}."],
    ["In the dark, pet a burning {noun}."],
    ["Write to the {noun}.", "Burn the letter.", "Mail the ashes."],
    ["Empty a stranger's {noun}."],
    ["While crying, hate a fake {noun}."],
    ["In secret, stare at all {noun}s."],
    ["While falling, flip your own {noun}."],
    ["Burn a microscopic {noun}."],
    ["With eyes closed, share a forgotten {noun}."],
    ["For a single moment, empty an invisible {noun}."],
    ["Blindfolded, mute a silent {noun}."],
    ["Paint all {noun}s."],
    ["Trembling, cut a microscopic {noun}."],
    ["At the perfect time, paint a wet {noun}."],
    ["Expose the real {noun}."],
    ["Scroll down.", "Until you see the {noun}.", "Close your eyes."],
    ["Flip a microscopic {noun}."],
    ["At the perfect time, sing to a perfect {noun}."],
    ["Ignore a future {noun}."],
    ["Forever, destroy the {noun}."],
    ["While falling, sing to a wet {noun}."],
    ["In front of strangers, dissolve a microscopic {noun}."],
    ["Like a prayer, bless a dead {noun}."],
    ["Trembling, count a fake {noun}."],
    ["Pet the first {noun}."],
    ["Curse a forgotten {noun}."],
    ["Trembling, paint all {noun}s."],
    ["Destroy the real {noun}."],
    ["Swallow a transparent {noun}."],
    ["While crying, cut the {noun}."],
    ["Naked, bury a stranger's {noun}."],
    ["Walking backwards, upload a future {noun}."],
    ["Swallow a microscopic {noun}."],
    ["Design a stranger's {noun}."],
    ["Throw a burning {noun}."],
    ["Bury a transparent {noun}."],
    ["In secret, reboot a broken {noun}."],
    ["Standing on one leg, escape from every {noun}."],
    ["Touch a microscopic {noun}."],
    ["At midnight, embrace a stranger's {noun}."],
    ["Embrace a stranger's {noun}."],
    ["Record the {noun}."],
    ["Screaming loudly, hate an invisible {noun}."],
    ["Destroy a perfect {noun}."],
    ["Smash the last {noun}."],
    ["Forget the last {noun}."],
    ["Like a prayer, bury a forgotten {noun}."],
    ["Like a prayer, step on all {noun}s."],
    ["Steal the {noun}.", "Return the {noun}.", "Steal it again."],
    ["Expose the {noun}."],
    ["While crying, step on a dead {noun}."],
    ["Lick a future {noun}."],
    ["With eyes closed, name the last {noun}."],
    ["Walking backwards, remember the first {noun}."],
    ["Give away a forgotten {noun}."],
    ["Trembling, remember the {noun}."],
    ["Bless the last {noun}."],
    ["In the dark, talk to the first {noun}."],
    ["Disassemble a forgotten {noun}."],
    ["For no reason, smash a microscopic {noun}."],
    ["Forever, empty your own {noun}."],
    ["Pet a burning {noun}."],
    ["In the dark, empty a dead {noun}."],
    ["Design the {noun}."],
    ["Touch an invisible {noun}."],
    ["Trembling, touch your own {noun}."],
    ["Blindfolded, dissolve a future {noun}."],
    ["Naked, disassemble a wet {noun}."],
    ["Record a perfect {noun}."],
    ["For no reason, lock up a broken {noun}."],
    ["While crying, crush a broken {noun}."],
    ["For no reason, stare at the {noun}."],
    ["In the dark, destroy a wet {noun}."],
    ["Standing on one leg, cut the real {noun}."],
    ["While falling, step on the first {noun}."],
    ["At the perfect time, hate all {noun}s."],
    ["With eyes closed, love a dead {noun}."],
    ["Decode a dead {noun}."],
    ["In front of strangers, bless a broken {noun}."],
    ["Like the {noun}.", "Unlike it after 1 minute.", "Repeat 10 times."],
    ["In complete silence, flip a transparent {noun}."],
    ["While crying, cut a perfect {noun}."],
    ["In secret, swallow the first {noun}."],
    ["At midnight, share the last {noun}."],
    ["Walking backwards, draw the first {noun}."],
    ["Screaming loudly, reboot a giant {noun}."],
    ["Trembling, reassemble a future {noun}."],
    ["Upside down, bless a microscopic {noun}."],
    ["Underwater, bury a wet {noun}."],
    ["In the dark, design your own {noun}."],
    ["With eyes closed, format a silent {noun}."],
    ["Block a burning {noun}."],
    ["Screaming loudly, lick an invisible {noun}."],
    ["Holding your breath, share the {noun}."],
    ["Naked, lick the last {noun}."],
    ["Standing on one leg, empty a stranger's {noun}."],
    ["Wait for the {noun}.", "It never arrives.", "Keep waiting."],
    ["For no reason, crush a silent {noun}."],
    ["Standing on one leg, delete the first {noun}."],
    ["Paint an invisible {noun}."],
    ["Flip an invisible {noun}."],
    ["At the perfect time, sing to a wet {noun}."],
    ["Underwater, split the real {noun}."],
    ["Hide a silent {noun}."],
    ["Holding your breath, measure a forgotten {noun}."],
    ["Love the {noun}.", "Hate the {noun}.", "Feel nothing."],
    ["Smiling, draw a giant {noun}."],
    ["Cut a future {noun}."],
    ["Destroy a microscopic {noun}."],
    ["Disassemble an imaginary {noun}."],
    ["Naked, love a broken {noun}."],
    ["Underwater, sing to the real {noun}."],
    ["Lock up a giant {noun}."],
    ["In secret, touch a wet {noun}."],
    ["Swallow a wet {noun}."],
    ["Forever, measure the first {noun}."],
    ["Walking backwards, record a giant {noun}."],
    ["Holding your breath, name a transparent {noun}."],
    ["Smiling, upload a fake {noun}."],
    ["Upside down, design a silent {noun}."],
    ["In the dark, expose a wet {noun}."],
    ["Expose a stranger's {noun}."],
    ["Open the {noun}.", "Close the {noun}."],
    ["Walking backwards, curse a silent {noun}."],
    ["Underwater, bless every {noun}."],
    ["Lick a stranger's {noun}."],
    ["Holding your breath, drop a silent {noun}."],
    ["With eyes closed, throw a fake {noun}."],
    ["With eyes closed, reassemble every {noun}."],
    ["For a single moment, reboot a giant {noun}."],
    ["In secret, disassemble a transparent {noun}."],
    ["In secret, sink a stranger's {noun}."],
    ["Like a prayer, sink a stranger's {noun}."],
    ["In secret, draw the {noun}."],
    ["Expose every {noun}."],
    ["Burn the {noun}.", "Gather the ashes.", "Scatter them."],
    ["In complete silence, steal a future {noun}."],
    ["In front of strangers, freeze a stranger's {noun}."],
    ["With eyes closed, freeze a broken {noun}."],
    ["Trembling, compress your own {noun}."],
    ["In secret, design the {noun}."],
    ["Remember every {noun}."],
    ["In secret, smash the {noun}."],
    ["In the dark, draw a forgotten {noun}."],
    ["Upside down, lock up the {noun}."],
    ["For a single moment, upload a giant {noun}."],
    ["In complete silence, download a fake {noun}."],
    ["Cut a transparent {noun}."],
    ["Blindfolded, design a silent {noun}."],
    ["Holding your breath, expose the first {noun}."],
    ["Blindfolded, destroy a silent {noun}."],
    ["Pray to the {noun}.", "Curse the {noun}.", "Remain silent."],
    ["Call the {noun}.", "No answer.", "Call again."],
    ["Trembling, escape from a burning {noun}."],
    ["Standing on one leg, download the {noun}."],
    ["Pet a microscopic {noun}."],
    ["At the perfect time, download a microscopic {noun}."],
    ["While crying, dissolve the real {noun}."],
    ["Forever, give away a transparent {noun}."],
    ["Forever, paint a future {noun}."],
    ["Format the {noun}."],
    ["Hide the {noun}.", "Forget where.", "Search forever."],
    ["Lick an invisible {noun}."],
    ["Hate a burning {noun}."],
    ["Underwater, embrace a future {noun}."],
    ["Smiling, curse a broken {noun}."],
    ["With eyes closed, pet an imaginary {noun}."],
    ["Underwater, measure a forgotten {noun}."],
    ["Forever, touch a broken {noun}."],
    ["Underwater, split the {noun}."],
    ["Stare at a broken {noun}."],
    ["Without any emotion, stare at a fake {noun}."],
    ["Naked, swallow a silent {noun}."],
    ["At midnight, throw a future {noun}."],
    ["Smiling, swallow a forgotten {noun}."],
    ["While falling, lick all {noun}s."],
    ["While crying, flip every {noun}."],
    ["Standing on one leg, steal the first {noun}."],
    ["Smash a future {noun}."],
    ["Naked, reassemble a broken {noun}."],
    ["Forget a giant {noun}."],
    ["With ears covered, bless a perfect {noun}."],
    ["In complete silence, weigh a giant {noun}."],
    ["Upside down, dissolve a silent {noun}."],
    ["Smiling, forget an invisible {noun}."],
    ["While falling, step on the {noun}."],
    ["While crying, hate every {noun}."],
    ["Smiling, format a burning {noun}."],
    ["With eyes closed, throw the {noun}."],
    ["Naked, embrace a microscopic {noun}."],
    ["At midnight, block a silent {noun}."],
    ["Forget your own {noun}."],
    ["Stare at a dead {noun}."],
    ["Trembling, curse your own {noun}."],
    ["Mute the {noun}.", "Block the {noun}.", "Forget the {noun}."],
    ["Paint a wet {noun}."],
    ["Like a prayer, freeze a burning {noun}."],
    ["Pet the {noun}."],
    ["Dissolve your own {noun}."],
    ["In complete silence, talk to the {noun}."],
    ["Weigh every {noun}."],
    ["Reboot a perfect {noun}."],
    ["In complete silence, measure a forgotten {noun}."],
    ["Walking backwards, hate the {noun}."],
    ["In the dark, empty a transparent {noun}."],
    ["Naked, compress the {noun}."],
    ["Block the {noun}."],
    ["For a single moment, flip the real {noun}."],
    ["Take a photo of the {noun}.", "Apply a filter.", "Delete it before posting."],
    ["Step on a dead {noun}."],
    ["Forever, block the first {noun}."],
    ["Crush the {noun}."],
    ["Lock up the {noun}."],
    ["Upside down, touch a broken {noun}."],
    ["Without any emotion, destroy a fake {noun}."],
    ["While crying, bury the {noun}."],
    ["With eyes closed, cut a stranger's {noun}."],
    ["Without thinking, bury a silent {noun}."],
    ["Upside down, expose an imaginary {noun}."],
    ["Share a transparent {noun}."],
    ["Drop a burning {noun}."],
    ["Naked, give away the {noun}."],
    ["In secret, burn a transparent {noun}."],
    ["Block the last {noun}."],
    ["Upside down, curse your own {noun}."],
    ["Naked, format a perfect {noun}."],
    ["Blindfolded, curse an imaginary {noun}."],
    ["Empty a wet {noun}."],
    ["Drop the real {noun}."],
    ["Delete the {noun}."],
    ["Without thinking, touch a stranger's {noun}."],
    ["In the dark, share a future {noun}."],
    ["Eat the {noun}.", "Spit it out.", "Bury it."],
    ["Empty a giant {noun}."],
    ["Give away a microscopic {noun}."],
    ["Naked, decode a giant {noun}."],
    ["Build a {noun}.", "Destroy it.", "Build it again."],
    ["Walking backwards, give away the first {noun}."],
    ["In secret, empty a broken {noun}."],
    ["Like a prayer, ignore the {noun}."],
    ["For a single moment, curse a transparent {noun}."],
    ["Upside down, smell the {noun}."],
    ["Love a transparent {noun}."],
    ["Delete the first {noun}."],
    ["Naked, record the {noun}."],
    ["At the perfect time, reboot a transparent {noun}."],
    ["In the dark, upload a burning {noun}."],
    ["Stare at a silent {noun}."],
    ["Burn a dead {noun}."],
    ["Split your own {noun}."],
    ["Remember a stranger's {noun}."],
    ["Forever, disassemble a broken {noun}."],
    ["Sink a stranger's {noun}."],
    ["Touch the {noun}."],
    ["Smell the {noun}."],
    ["While crying, mute an imaginary {noun}."],
    ["With ears covered, forget a microscopic {noun}."],
    ["While falling, lock up a wet {noun}."],
    ["Smiling, talk to your own {noun}."],
    ["For no reason, name the first {noun}."],
    ["Weigh a perfect {noun}."],
    ["Blindfolded, swallow every {noun}."],
    ["Remember the {noun}."],
    ["Like a prayer, pet an imaginary {noun}."],
    ["Bless a dead {noun}."],
    ["Flip the {noun}."],
    ["With eyes closed, sing to every {noun}."],
    ["At the perfect time, design a fake {noun}."],
    ["Naked, freeze a forgotten {noun}."],
    ["Screaming loudly, measure the {noun}."],
    ["Holding your breath, drop the {noun}."],
    ["Blindfolded, ignore the {noun}."],
    ["Forever, unzip a dead {noun}."],
    ["Bury a burning {noun}."],
    ["Without thinking, pet a forgotten {noun}."],
    ["Upside down, weigh a silent {noun}."],
    ["Upside down, share a fake {noun}."],
    ["Trembling, reboot a dead {noun}."],
    ["Without thinking, flip a dead {noun}."],
    ["Blindfolded, paint your own {noun}."],
    ["Curse a future {noun}."],
    ["In secret, burn a broken {noun}."],
    ["Like a prayer, give away every {noun}."],
    ["Smiling, swallow a perfect {noun}."],
    ["Standing on one leg, block your own {noun}."],
    ["In secret, step on a burning {noun}."],
    ["Without thinking, measure a perfect {noun}."],
    ["In front of strangers, unzip an invisible {noun}."],
    ["Sing to the {noun}."],
    ["Trembling, love an imaginary {noun}."],
    ["While falling, love a forgotten {noun}."],
    ["Smiling, lick an invisible {noun}."],
    ["Unzip the last {noun}."],
    ["At the perfect time, smell the {noun}."],
    ["Bless the {noun}."],
    ["Blindfolded, block the real {noun}."],
    ["Screaming loudly, name a broken {noun}."],
    ["Turn on the {noun}.", "Turn off the {noun}.", "Repeat."],
    ["Touch a forgotten {noun}."],
    ["Sink a transparent {noun}."],
    ["For a single moment, count a perfect {noun}."],
    ["Without any emotion, measure every {noun}."],
    ["Upside down, step on the {noun}."],
    ["Disassemble a giant {noun}."]
];
